# To get started with security, check out the documentation:
# http://symfony.com/doc/current/book/security.html
security:

    # http://symfony.com/doc/current/book/security.html#where-do-users-come-from-user-providers
    providers:
        our_db_provider:
            entity:
                class: AppBundle:Admin                      b
                property: username

        in_memory:
            memory:
                users:
                    admin:
                          password: admin
                          roles: 'ROLE_ADMIN'
#                    employer:
#                            password: employer
#                            roles: 'ROLE_EMPLOYER'
#                    student:
#                            password: student
#                            roles: 'ROLE_STUDENT'

    firewalls:
        # disables authentication for assets and the profiler, adapt it according to your needs
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false

        main:
            pattern: ^/
            anonymous: ~
            # activate different ways to authenticate

            http_basic: ~
#            provider: our_db_provider
            # http://symfony.com/doc/current/book/security.html#a-configuring-how-your-users-will-authenticate

            # form_login: ~
            # http://symfony.com/doc/current/cookbook/security/form_login_setup.html

    access_control:
        # require ROLE_ADMIN for /employer*
        - { path: ^/employer, roles: ROLE_ADMIN }


        # require ROLE_STUDENT for /student*
        #- { path: ^/student, roles: ROLE_STUDENT }

        # require ROLE_ADMIN for /student*
        - { path: ^/student, roles: ROLE_ADMIN }

    encoders:
#            Symfony\Component\Security\Core\User\User: plaintext
            AppBundle\Entity\Employer:
                algorithm: bcrypt
                cost: 12

            AppBundle\Entity\Student:
                algorithm: bcrypt
                cost: 12